/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestColorsRouteImport } from './routes/test-colors'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutBuildersRouteImport } from './routes/_layout/builders'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutProfileAccountIdRouteImport } from './routes/_layout/profile/$accountId'
import { Route as LayoutBuildersBuilderIdRouteImport } from './routes/_layout/builders/$builderId'
import { Route as LayoutAuthenticatedSettingsRouteImport } from './routes/_layout/_authenticated/settings'
import { Route as LayoutAuthenticatedAdminRouteImport } from './routes/_layout/_authenticated/_admin'
import { Route as LayoutAuthenticatedChatIndexRouteImport } from './routes/_layout/_authenticated/chat/index'
import { Route as LayoutAuthenticatedKeysKeyRouteImport } from './routes/_layout/_authenticated/keys/$key'
import { Route as LayoutAuthenticatedAdminDashboardRouteImport } from './routes/_layout/_authenticated/_admin/dashboard'

const TestColorsRoute = TestColorsRouteImport.update({
  id: '/test-colors',
  path: '/test-colors',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBuildersRoute = LayoutBuildersRouteImport.update({
  id: '/builders',
  path: '/builders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileAccountIdRoute = LayoutProfileAccountIdRouteImport.update({
  id: '/profile/$accountId',
  path: '/profile/$accountId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBuildersBuilderIdRoute = LayoutBuildersBuilderIdRouteImport.update({
  id: '/$builderId',
  path: '/$builderId',
  getParentRoute: () => LayoutBuildersRoute,
} as any)
const LayoutAuthenticatedSettingsRoute =
  LayoutAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedAdminRoute =
  LayoutAuthenticatedAdminRouteImport.update({
    id: '/_admin',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedChatIndexRoute =
  LayoutAuthenticatedChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedKeysKeyRoute =
  LayoutAuthenticatedKeysKeyRouteImport.update({
    id: '/keys/$key',
    path: '/keys/$key',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedAdminDashboardRoute =
  LayoutAuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/test-colors': typeof TestColorsRoute
  '/builders': typeof LayoutBuildersRouteWithChildren
  '/login': typeof LayoutLoginRoute
  '/settings': typeof LayoutAuthenticatedSettingsRoute
  '/builders/$builderId': typeof LayoutBuildersBuilderIdRoute
  '/profile/$accountId': typeof LayoutProfileAccountIdRoute
  '/dashboard': typeof LayoutAuthenticatedAdminDashboardRoute
  '/keys/$key': typeof LayoutAuthenticatedKeysKeyRoute
  '/chat/': typeof LayoutAuthenticatedChatIndexRoute
}
export interface FileRoutesByTo {
  '/test-colors': typeof TestColorsRoute
  '/': typeof LayoutIndexRoute
  '/builders': typeof LayoutBuildersRouteWithChildren
  '/login': typeof LayoutLoginRoute
  '/settings': typeof LayoutAuthenticatedSettingsRoute
  '/builders/$builderId': typeof LayoutBuildersBuilderIdRoute
  '/profile/$accountId': typeof LayoutProfileAccountIdRoute
  '/dashboard': typeof LayoutAuthenticatedAdminDashboardRoute
  '/keys/$key': typeof LayoutAuthenticatedKeysKeyRoute
  '/chat': typeof LayoutAuthenticatedChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/test-colors': typeof TestColorsRoute
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/builders': typeof LayoutBuildersRouteWithChildren
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_authenticated/_admin': typeof LayoutAuthenticatedAdminRouteWithChildren
  '/_layout/_authenticated/settings': typeof LayoutAuthenticatedSettingsRoute
  '/_layout/builders/$builderId': typeof LayoutBuildersBuilderIdRoute
  '/_layout/profile/$accountId': typeof LayoutProfileAccountIdRoute
  '/_layout/_authenticated/_admin/dashboard': typeof LayoutAuthenticatedAdminDashboardRoute
  '/_layout/_authenticated/keys/$key': typeof LayoutAuthenticatedKeysKeyRoute
  '/_layout/_authenticated/chat/': typeof LayoutAuthenticatedChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test-colors'
    | '/builders'
    | '/login'
    | '/settings'
    | '/builders/$builderId'
    | '/profile/$accountId'
    | '/dashboard'
    | '/keys/$key'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/test-colors'
    | '/'
    | '/builders'
    | '/login'
    | '/settings'
    | '/builders/$builderId'
    | '/profile/$accountId'
    | '/dashboard'
    | '/keys/$key'
    | '/chat'
  id:
    | '__root__'
    | '/_layout'
    | '/test-colors'
    | '/_layout/_authenticated'
    | '/_layout/builders'
    | '/_layout/login'
    | '/_layout/'
    | '/_layout/_authenticated/_admin'
    | '/_layout/_authenticated/settings'
    | '/_layout/builders/$builderId'
    | '/_layout/profile/$accountId'
    | '/_layout/_authenticated/_admin/dashboard'
    | '/_layout/_authenticated/keys/$key'
    | '/_layout/_authenticated/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  TestColorsRoute: typeof TestColorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-colors': {
      id: '/test-colors'
      path: '/test-colors'
      fullPath: '/test-colors'
      preLoaderRoute: typeof TestColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/builders': {
      id: '/_layout/builders'
      path: '/builders'
      fullPath: '/builders'
      preLoaderRoute: typeof LayoutBuildersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/$accountId': {
      id: '/_layout/profile/$accountId'
      path: '/profile/$accountId'
      fullPath: '/profile/$accountId'
      preLoaderRoute: typeof LayoutProfileAccountIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/builders/$builderId': {
      id: '/_layout/builders/$builderId'
      path: '/$builderId'
      fullPath: '/builders/$builderId'
      preLoaderRoute: typeof LayoutBuildersBuilderIdRouteImport
      parentRoute: typeof LayoutBuildersRoute
    }
    '/_layout/_authenticated/settings': {
      id: '/_layout/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/_admin': {
      id: '/_layout/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/chat/': {
      id: '/_layout/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof LayoutAuthenticatedChatIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/keys/$key': {
      id: '/_layout/_authenticated/keys/$key'
      path: '/keys/$key'
      fullPath: '/keys/$key'
      preLoaderRoute: typeof LayoutAuthenticatedKeysKeyRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/_admin/dashboard': {
      id: '/_layout/_authenticated/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedAdminDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRoute
    }
  }
}

interface LayoutAuthenticatedAdminRouteChildren {
  LayoutAuthenticatedAdminDashboardRoute: typeof LayoutAuthenticatedAdminDashboardRoute
}

const LayoutAuthenticatedAdminRouteChildren: LayoutAuthenticatedAdminRouteChildren =
  {
    LayoutAuthenticatedAdminDashboardRoute:
      LayoutAuthenticatedAdminDashboardRoute,
  }

const LayoutAuthenticatedAdminRouteWithChildren =
  LayoutAuthenticatedAdminRoute._addFileChildren(
    LayoutAuthenticatedAdminRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedAdminRoute: typeof LayoutAuthenticatedAdminRouteWithChildren
  LayoutAuthenticatedSettingsRoute: typeof LayoutAuthenticatedSettingsRoute
  LayoutAuthenticatedKeysKeyRoute: typeof LayoutAuthenticatedKeysKeyRoute
  LayoutAuthenticatedChatIndexRoute: typeof LayoutAuthenticatedChatIndexRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedAdminRoute: LayoutAuthenticatedAdminRouteWithChildren,
  LayoutAuthenticatedSettingsRoute: LayoutAuthenticatedSettingsRoute,
  LayoutAuthenticatedKeysKeyRoute: LayoutAuthenticatedKeysKeyRoute,
  LayoutAuthenticatedChatIndexRoute: LayoutAuthenticatedChatIndexRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutBuildersRouteChildren {
  LayoutBuildersBuilderIdRoute: typeof LayoutBuildersBuilderIdRoute
}

const LayoutBuildersRouteChildren: LayoutBuildersRouteChildren = {
  LayoutBuildersBuilderIdRoute: LayoutBuildersBuilderIdRoute,
}

const LayoutBuildersRouteWithChildren = LayoutBuildersRoute._addFileChildren(
  LayoutBuildersRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutBuildersRoute: typeof LayoutBuildersRouteWithChildren
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProfileAccountIdRoute: typeof LayoutProfileAccountIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutBuildersRoute: LayoutBuildersRouteWithChildren,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProfileAccountIdRoute: LayoutProfileAccountIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  TestColorsRoute: TestColorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
