/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutAuthenticatedIndexRouteImport } from './routes/_layout/_authenticated/index'
import { Route as LayoutAuthenticatedSettingsRouteImport } from './routes/_layout/_authenticated/settings'
import { Route as LayoutAuthenticatedAdminRouteImport } from './routes/_layout/_authenticated/_admin'
import { Route as LayoutAuthenticatedChatIndexRouteImport } from './routes/_layout/_authenticated/chat/index'
import { Route as LayoutAuthenticatedKeysKeyRouteImport } from './routes/_layout/_authenticated/keys/$key'
import { Route as LayoutAuthenticatedAdminDashboardRouteImport } from './routes/_layout/_authenticated/_admin/dashboard'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedIndexRoute =
  LayoutAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedSettingsRoute =
  LayoutAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedAdminRoute =
  LayoutAuthenticatedAdminRouteImport.update({
    id: '/_admin',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedChatIndexRoute =
  LayoutAuthenticatedChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedKeysKeyRoute =
  LayoutAuthenticatedKeysKeyRouteImport.update({
    id: '/keys/$key',
    path: '/keys/$key',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedAdminDashboardRoute =
  LayoutAuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutAuthenticatedIndexRoute
  '/login': typeof LayoutLoginRoute
  '/settings': typeof LayoutAuthenticatedSettingsRoute
  '/dashboard': typeof LayoutAuthenticatedAdminDashboardRoute
  '/keys/$key': typeof LayoutAuthenticatedKeysKeyRoute
  '/chat/': typeof LayoutAuthenticatedChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutAuthenticatedIndexRoute
  '/login': typeof LayoutLoginRoute
  '/settings': typeof LayoutAuthenticatedSettingsRoute
  '/dashboard': typeof LayoutAuthenticatedAdminDashboardRoute
  '/keys/$key': typeof LayoutAuthenticatedKeysKeyRoute
  '/chat': typeof LayoutAuthenticatedChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/_authenticated/_admin': typeof LayoutAuthenticatedAdminRouteWithChildren
  '/_layout/_authenticated/settings': typeof LayoutAuthenticatedSettingsRoute
  '/_layout/_authenticated/': typeof LayoutAuthenticatedIndexRoute
  '/_layout/_authenticated/_admin/dashboard': typeof LayoutAuthenticatedAdminDashboardRoute
  '/_layout/_authenticated/keys/$key': typeof LayoutAuthenticatedKeysKeyRoute
  '/_layout/_authenticated/chat/': typeof LayoutAuthenticatedChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/dashboard'
    | '/keys/$key'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/settings' | '/dashboard' | '/keys/$key' | '/chat'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_authenticated'
    | '/_layout/login'
    | '/_layout/_authenticated/_admin'
    | '/_layout/_authenticated/settings'
    | '/_layout/_authenticated/'
    | '/_layout/_authenticated/_admin/dashboard'
    | '/_layout/_authenticated/keys/$key'
    | '/_layout/_authenticated/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/': {
      id: '/_layout/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/settings': {
      id: '/_layout/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/_admin': {
      id: '/_layout/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/chat/': {
      id: '/_layout/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof LayoutAuthenticatedChatIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/keys/$key': {
      id: '/_layout/_authenticated/keys/$key'
      path: '/keys/$key'
      fullPath: '/keys/$key'
      preLoaderRoute: typeof LayoutAuthenticatedKeysKeyRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/_admin/dashboard': {
      id: '/_layout/_authenticated/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedAdminDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRoute
    }
  }
}

interface LayoutAuthenticatedAdminRouteChildren {
  LayoutAuthenticatedAdminDashboardRoute: typeof LayoutAuthenticatedAdminDashboardRoute
}

const LayoutAuthenticatedAdminRouteChildren: LayoutAuthenticatedAdminRouteChildren =
  {
    LayoutAuthenticatedAdminDashboardRoute:
      LayoutAuthenticatedAdminDashboardRoute,
  }

const LayoutAuthenticatedAdminRouteWithChildren =
  LayoutAuthenticatedAdminRoute._addFileChildren(
    LayoutAuthenticatedAdminRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedAdminRoute: typeof LayoutAuthenticatedAdminRouteWithChildren
  LayoutAuthenticatedSettingsRoute: typeof LayoutAuthenticatedSettingsRoute
  LayoutAuthenticatedIndexRoute: typeof LayoutAuthenticatedIndexRoute
  LayoutAuthenticatedKeysKeyRoute: typeof LayoutAuthenticatedKeysKeyRoute
  LayoutAuthenticatedChatIndexRoute: typeof LayoutAuthenticatedChatIndexRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedAdminRoute: LayoutAuthenticatedAdminRouteWithChildren,
  LayoutAuthenticatedSettingsRoute: LayoutAuthenticatedSettingsRoute,
  LayoutAuthenticatedIndexRoute: LayoutAuthenticatedIndexRoute,
  LayoutAuthenticatedKeysKeyRoute: LayoutAuthenticatedKeysKeyRoute,
  LayoutAuthenticatedChatIndexRoute: LayoutAuthenticatedChatIndexRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutLoginRoute: typeof LayoutLoginRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutLoginRoute: LayoutLoginRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
